kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - name: main
      protocol: TCP
      port: 8080
      targetPort: 80
    - name: secondary
      protocol: TCP
      port: 80
      targetPort: 80
